//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC_Channel9_bot.Resources.en_us {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POC_Channel9_bot.Resources.en_us.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excuse my limited dictionary, I did not get what you mean. You can get more information here http://POC_Channel9_bot.azurewebsites.net/.
        /// </summary>
        internal static string defaultMessage {
            get {
                return ResourceManager.GetString("defaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featured.
        /// </summary>
        internal static string featured {
            get {
                return ResourceManager.GetString("featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest featured video&apos;s title is: {0}. Here is a link to go watch it: {1}.
        /// </summary>
        internal static string featuredVideoResponse {
            get {
                return ResourceManager.GetString("featuredVideoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there! This is a prototype for the Channel 9 bot! Ask me about channel9 news!
        /// I can tell you about the last featured video, the most viewed video this week or this month, the last event, if there is a live event on Channel9.
        /// I can also give you the top 5 videos about any technology that interests you, just write &quot;Search [term]&quot;
        ///Have fun!.
        /// </summary>
        internal static string helloMessage {
            get {
                return ResourceManager.GetString("helloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest event.
        /// </summary>
        internal static string latestEvent {
            get {
                return ResourceManager.GetString("latestEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest event on Channel 9 is: {0}. Here is a link to go watch it: {1}.
        /// </summary>
        internal static string latestEventResponse {
            get {
                return ResourceManager.GetString("latestEventResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live.
        /// </summary>
        internal static string live {
            get {
                return ResourceManager.GetString("live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a live event on Channel 9 now: {0}. Here is a link to go watch it: {1}.
        /// </summary>
        internal static string liveEventResponse {
            get {
                return ResourceManager.GetString("liveEventResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most viewed.
        /// </summary>
        internal static string mostViewed {
            get {
                return ResourceManager.GetString("mostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most viewed video this month is: {0}. It has {1} views. Here is a link to go watch it: {2}.
        /// </summary>
        internal static string mostViewedThisMonthResponse {
            get {
                return ResourceManager.GetString("mostViewedThisMonthResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most viewed video this week is: {0}. It has {1} views. Here is a link to go watch it: {2}.
        /// </summary>
        internal static string mostViewedThisWeekResponse {
            get {
                return ResourceManager.GetString("mostViewedThisWeekResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have data for the whole year but I can tell you about the most viewed video this week or this month..
        /// </summary>
        internal static string mostViewedThisYearResponse {
            get {
                return ResourceManager.GetString("mostViewedThisYearResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like there is no Live events on Channel9 right now..
        /// </summary>
        internal static string noLiveEventResponse {
            get {
                return ResourceManager.GetString("noLiveEventResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the Top 5 videos I found on Channel 9 about {0}.
        /// </summary>
        internal static string SearchResponse {
            get {
                return ResourceManager.GetString("SearchResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not found any result on Channel 9 about {0}.
        /// </summary>
        internal static string SearchResponseFail {
            get {
                return ResourceManager.GetString("SearchResponseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this month.
        /// </summary>
        internal static string thisMonth {
            get {
                return ResourceManager.GetString("thisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        internal static string thisWeek {
            get {
                return ResourceManager.GetString("thisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this year.
        /// </summary>
        internal static string thisYear {
            get {
                return ResourceManager.GetString("thisYear", resourceCulture);
            }
        }
    }
}
